name: 'Configure thiscovery test environment'
description: 'Configures GitHub Action pipelines to use as test environment the AWS account of the developer who initiated the pipeline (actor)'
inputs:
  actor2env_map:
    description: 'JSON string mapping GitHub actors to AWS account parameters'
    required: true

runs:
  using: "composite"
  steps:
    # Configure target test account based on actor, using actor2env_map
    - name: Resolve actor config and set environment variables for AWS account
      shell: bash
      run: |
        echo "AWS_TEST_ACCOUNT=${{ fromJson(inputs.actor2env_map)[github.actor]['account_number']}}" >> $GITHUB_ENV
        echo "AWS_TEST_ENV=${{ fromJson(inputs.actor2env_map)[github.actor]['test_environment']}}" >> $GITHUB_ENV
        echo "THISCOVERY_EVENT_BUS_NAME=${{ fromJson(inputs.actor2env_map)[github.actor]['thiscovery-event-bus']}}" >> $GITHUB_ENV

    - name: Abort workflow if actor unknown
      shell: bash
      run: |
        if [ -z ${{ env.AWS_TEST_ENV }} ]; then
          echo "Actor ${{ github.actor }} unknown. Aborting workflow"
          exit 1
        fi

    - name: Set additional env variables
      shell: bash
      run: |
        echo "SECRETS_NAMESPACE=/${AWS_TEST_ENV}/" >> $GITHUB_ENV
        echo "UNIT_TEST_NAMESPACE=/${AWS_TEST_ENV}/" >> $GITHUB_ENV
        echo "TEST_ON_AWS=True" >> $GITHUB_ENV
        echo "TESTING_ACCOUNT_DEPLOYMENT_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-devops-${AWS_TEST_ENV}-${AWS_REGION}-PipelineExec" >> $GITHUB_ENV
        echo "TESTING_ACCOUNT_TEST_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-dev-setup-${AWS_TEST_ENV}-${AWS_REGION}-TestingExec" >> $GITHUB_ENV
        echo "ARTIFACTS_BUCKET=thiscovery-devops-${AWS_TEST_ENV}-deployment-artifacts" >> $GITHUB_ENV
        echo "CLOUDFORMATION_EXECUTION_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-devops-${AWS_TEST_ENV}-${AWS_REGION}-CFExec" >> $GITHUB_ENV
        echo "DEPLOYMENT_METHOD=github_actions" >> $GITHUB_ENV
        echo "PACKAGED_TEMPLATE=${{ env.STACK_NAME }}-packaged-${{ env.AWS_TEST_ENV }}.yaml" >> $GITHUB_ENV

