name: 'Configure thiscovery test environment'
description: 'Configures GitHub Action pipelines to use as test environment the AWS account of the developer who initiated the pipeline (actor)'
inputs:
  afs25_account:
    description: 'AWS account number for afs25'
    required: true
  sem86_account:
    description: 'AWS account number for sem86'
    required: true
  amp205_account:
    description: 'AWS account number for amp205'
    required: true
runs:
  using: "composite"
  steps:
    # Configure target test account based on actor
    - if: ${{ github.actor == 'afs25' }}
      name: Sets env vars for afs25
      shell: bash
      run: |
        echo "AWS_TEST_ACCOUNT=${{ inputs.afs25_account }}" >> $GITHUB_ENV
        echo "AWS_TEST_ENV=test-afs25" >> $GITHUB_ENV
  
    - if: ${{ github.actor == 'sophiemachin' }}
      name: Sets env vars for sem86
      shell: bash
      run: |
        echo "AWS_TEST_ACCOUNT=${{ inputs.sem86_account }}" >> $GITHUB_ENV
        echo "AWS_TEST_ENV=test-sem86" >> $GITHUB_ENV

    - if: ${{ github.actor == 'this-andy' }}
      name: Sets env vars for amp205
      shell: bash
      run: |
        echo "AWS_TEST_ACCOUNT=${{ inputs.amp205_account }}" >> $GITHUB_ENV
        echo "AWS_TEST_ENV=test-amp205" >> $GITHUB_ENV

    - if: ${{ github.actor == 'alistairclark' }}
      name: Sets env vars for afs25
      shell: bash
      run: |
        echo "AWS_TEST_ACCOUNT=${{ inputs.afs25_account }}" >> $GITHUB_ENV
        echo "AWS_TEST_ENV=test-afs25" >> $GITHUB_ENV
  
    - name: Abort workflow if actor unknown
      shell: bash
      run: |
        if [ -z ${{ env.AWS_TEST_ENV }} ]; then
          echo "Actor ${{ github.actor }} unknown. Aborting workflow"
          exit 1
        fi

    - name: Set additional env variables
      shell: bash
      run: |
        echo "SECRETS_NAMESPACE=/${AWS_TEST_ENV}/" >> $GITHUB_ENV
        echo "UNIT_TEST_NAMESPACE=/${AWS_TEST_ENV}/" >> $GITHUB_ENV
        echo "TEST_ON_AWS=True" >> $GITHUB_ENV
        echo "TESTING_ACCOUNT_DEPLOYMENT_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-devops-${AWS_TEST_ENV}-${AWS_REGION}-PipelineExec" >> $GITHUB_ENV
        echo "TESTING_ACCOUNT_TEST_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-dev-setup-${AWS_TEST_ENV}-${AWS_REGION}-TestingExec" >> $GITHUB_ENV
        echo "ARTIFACTS_BUCKET=thiscovery-devops-${AWS_TEST_ENV}-deployment-artifacts" >> $GITHUB_ENV
        echo "CLOUDFORMATION_EXECUTION_ROLE=arn:aws:iam::${AWS_TEST_ACCOUNT}:role/thiscovery-devops-${AWS_TEST_ENV}-${AWS_REGION}-CFExec" >> $GITHUB_ENV
        echo "DEPLOYMENT_METHOD=github_actions" >> $GITHUB_ENV
        echo "PACKAGED_TEMPLATE=${{ env.STACK_NAME }}-packaged-${{ env.AWS_TEST_ENV }}.yaml" >> $GITHUB_ENV

